# https://adamtheautomator.com/windows-docker-image-from-dockerfile-docker-build/
# https://www.youtube.com/watch?v=zJ6WbK9zFpI
# https://www.youtube.com/watch?v=pGYAg7TMmp0&t=0s&list=PLEOJBbtByx0JcTW4_KWvS1lBTAQWh9LxK&index=3
# https://dev.to/phuonghau98/yet-another-way-to-containerize-your-react-app-with-docker-multi-stage-build-3n6